language: ruby

rvm:
 - 1.9.3

script:
 - bundle exec rake db:migrate --trace
 - RAILS_ENV=test bundle exec rake db:migrate --trace
 - bundle exec rake db:test:prepare
 - bundle exec rspec -f d spec/

 deploy:
   provider: heroku
   api_key: "b6e22d38-edec-4521-98be-2b8027f13540"
   app: joen-ratebeer
   run: "rake db:migrate"
   run: "rake db:reset"