language: ruby

rvm:
 - 1.9.3

script:
 - bundle exec rake db:migrate --trace
 - RAILS_ENV=test bundle exec rake db:migrate --trace
 - bundle exec rake db:test:prepare
 - bundle exec rspec -f d spec/

deploy:
  provider: heroku
  api_key:
    secure: X3YdeJdChXwmo/JVCH+WYncn+JLyrg0/TvzvxZqdA8jW4EUvD8S+qUtXEb4m0/WOH6fCf/JpFFGjjBd9HWTVN+jPhnLGKSZsGE0eQ4xdUlLkKH5mISkjHcc9GoEY4TLiWZN2HJmJ2SqW2MQXkr/hCLV0o2e92s7dIIB5fzYy8UI=
  app: joen-ratebeer
  on:
    repo: Divinare/ratebeer
